spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mine&rewriteBatchedStatements=true
    username: developer
    password: qwer1234

  jpa:
    show-sql: true
    open-in-view: false #default : true이기에 수정해야 함.
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: '네이버 메일 계정 아이디'
    password: '네이버 메일 계정 비밀번호'
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
            enable: true
        debug: false
  sql:
    init:
      mode: always

  session:
    expire-seconds: 86400

  ai:
    openai:
      api-key: 'open ai 키 입력'

  profiles:
    include: dev

server:
  servlet:
    session:
      cookie:
        http-only: true
        path: /
        secure: true
        same-site: none
        max-age: 86400 # 하루
        domain: 도메인 명 입력

elevenlabs:
  api-key: 'eleven labs api 키 입력'