spring:
  session:
    expire-seconds: 86400 #
    store-type: redis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://khj745700.iptime.org:3306/mine
    username: developer
    password: qwer1234

  data:
    redis:
      host: khj745700.iptime.org
      port: 6379
