spring:
  session:
    expire-seconds: 86400 #
    store-type: redis
  redis:
    namespace: mine:session

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mine
    username: admin
    password: qwer1234

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue.my-name: chat-queue-springboot
  queue.fastapi-name: chat-queue-fastapi
  queue.fastapi-batch-name: batch-queue-fastapi
  exchange.name: amq.direct
  routing.fast-api-key: fast-api-server
  routing.fast-api-batch-key: fast-api-server-batch
  routing.my-key: spring-chat-server


server:
  servlet:
    session:
      cookie:
        http-only: true
        path: /
        secure: true
        same-site: none
        max-age: 3600
