version: '3.8'

services:
  app:
    build: ./application/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mine
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "qwer1234"

  chat:
    build: ./socket/
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mine
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "qwer1234"

  redis:
    image: redis



  mysql:
    image: mysql
    ports:
      - "3306:3306" # MySQL 기본 포트는 3306입니다.
    environment:
      MYSQL_DATABASE: mine
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'qwer1234'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672" # RabbitMQ 기본 포트
      - "15672:15672" # 관리 인터페이스 포트

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - chat
      - rabbitmq
