version: '3.8'

services:
  app:
    container_name: app
    build: ./application/
    ports:
      - "8081:8080"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mine
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "qwer1234"
      TZ: "Asia/Seoul"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/"]
      interval: 10s
      timeout: 2s
      retries: 100

  chat:
    container_name: chat
    build: ./socket/
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mine
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "qwer1234"
      TZ: "Asia/Seoul"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/"]
      interval: 10s
      timeout: 2s
      retries: 100



  redis:
    container_name: redis
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 2s
      retries: 100
    environment:
      TZ: "Asia/Seoul"

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    ports:
      - "3306:3306" # MySQL 기본 포트는 3306입니다.
    environment:
      MYSQL_DATABASE: mine
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'qwer1234'
      TZ: "Asia/Seoul"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: "Asia/Seoul"
    ports:
      - "5672:5672" # RabbitMQ 기본 포트
      - "15672:15672" # 관리 인터페이스 포트
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 3s
      retries: 100

  ai:
    container_name: ai
    build: ./ai/
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      chat:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always
    environment:
      TZ: "Asia/Seoul"

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      rabbitmq:
        condition: service_healthy
      chat:
        condition: service_healthy
      app:
        condition: service_healthy
    volumes:
      - /home/ubuntu/data/nginx/pki-validation:/usr/share/nginx/html/.well-known/pki-validation
      - /home/ubuntu/data/nginx/ssl:/etc/ssl/i11d106.p.ssafy.io
    environment:
      TZ: "Asia/Seoul"
